.TH SKIP 1
.SH NAME
skip \- skip text between two strings

.SH SYNOPSIS
skip BEGIN END

.SH DESCRIPTION
skip is a filter that skips the parts of the input text between
BEGIN and END. It reads standard input and writes the standard output
and does not regard newlines. When finding the end of a file, it
stops, even if the current position is after a BEGIN.

.SH EXAMPLES
.PP
.fi
.RS
$ skip '<' '>'
.RE
.fi
somewhat strips html from the input.
.PP
.fi
.RS
$ skip '<script' '</script>'
.RE
.fi
prints the contents of a web-page without the javascript.

.SH STATUS
0 on success and 1 when it prints the usage.

.SH BUGS
skip could be a lot more general in what it does. there are plans for another
utility that will do this.

.SH AUTHOR
pranomestro@gmail.com
