.Dd May 11, 2017
.Dt SKIP 1
.Os

.Sh NAME
.Nm skip
.Nd skip the input between two strings

.Sh SYNOPSIS
.Nm
.Ar begin
.Ar end

.Sh DESCRIPTION
.Nm
is a filter that skips the the parts of its input that are delimited
by the strings
.Ar begin
and
.Ar end ,
inclusively. This includes newlines.

.Sh EXAMPLES
Somewhat strip HTML from the input:
.Pp
.Dl $ curl http://www.ozarkia.net/bill/anarchism/library/rg-anarcho-cap.html | skip '<' '>'
.Pp
Somewhat strip the javascript from a webpage:
.Pp
.Dl $ curl https://en.wikipedia.org/wiki/Main_Page | skip '<script' '</script>'

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
.Nm
could be a lot more general.

.Sh SEE ALSO
.Xr curl 1 ,
.Xr sed 1 ,
.Xr tr 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomestro@gmail.com
